### ISSUE TITLE
RUNNING ERROR

### ISSUE THREAD

**Issue by N-Kingsley** [mjacar/pytorch-nec#8]
How to solve the problem below.

Episode 0
Total Reward: -19.0
E:\profession\pycharm\tensorflow\pytorch-nec-master\nec_agent.py:96: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  action = torch.cat(q_estimates).max(0)[1].data[0]
d:\anaconda\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "E:/profession/pycharm/tensorflow/pytorch-nec-master/run_nec.py", line 35, in <module>
    main(args.env, args.embedding_size)
  File "E:/profession/pycharm/tensorflow/pytorch-nec-master/run_nec.py", line 23, in main
    reward = agent.episode()
  File "E:\profession\pycharm\tensorflow\pytorch-nec-master\nec_agent.py", line 179, in episode
    self.update()
  File "E:\profession\pycharm\tensorflow\pytorch-nec-master\nec_agent.py", line 133, in update
    embedding_index = dnd.get_index(state_embedding)
  File "E:\profession\pycharm\tensorflow\pytorch-nec-master\dnd.py", line 42, in get_index
    self.commit_insert()
  File "E:\profession\pycharm\tensorflow\pytorch-nec-master\dnd.py", line 80, in commit_insert
    torch.cat([self.values.data, self.values_to_be_inserted], 0))
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 1 at c:\programdata\miniconda3\conda-bld\pytorch-cpu_1532498166916\work\aten\src\th\generic/THTensorMath.cpp:3607

Process finished with exit code 1

**Comment by N-Kingsley** [comment]
I

**Comment by N-Kingsley** [comment]
The problem above have been solved.
What is LRU property? And what's  the role of  'self.move_to_back' in dnd.py
